# 데이터셋 라벨 컬럼 (PII 제외 36개) 및 한국어 표시명 매핑

LABEL_COLUMNS = [
    "related",
    "request",
    "offer",
    "aid_related",
    "medical_help",
    "medical_products",
    "search_and_rescue",
    "security",
    "military",
    "child_alone",
    "water",
    "food",
    "shelter",
    "clothing",
    "money",
    "missing_people",
    "refugees",
    "death",
    "other_aid",
    "infrastructure_related",
    "transport",
    "buildings",
    "electricity",
    "tools",
    "hospitals",
    "shops",
    "aid_centers",
    "other_infrastructure",
    "weather_related",
    "floods",
    "storm",
    "fire",
    "earthquake",
    "cold",
    "other_weather",
    "direct_report",
]

# related/request/offer/aid_related/infrastructure_related/weather_related/direct_report는
# "재난 관련 여부·신고 형식" 등을 나타내는 메타 라벨이라 화면의 "긴급 지원 유형" 목록에는
# 적합하지 않다. 구조 요청 여부 판단(core/scoring.py)에는 계속 전체 라벨 확률을 사용한다.
NON_AID_TYPE_LABELS = {
    "related",
    "request",
    "offer",
    "aid_related",
    "infrastructure_related",
    "weather_related",
    "direct_report",
}

AID_TYPE_LABEL_COLUMNS = [c for c in LABEL_COLUMNS if c not in NON_AID_TYPE_LABELS]

LABEL_KO = {
    "related": "관련성",
    "request": "지원 요청",
    "offer": "지원 제공",
    "aid_related": "구호 관련",
    "medical_help": "의료 지원",
    "medical_products": "의료 물품",
    "search_and_rescue": "수색 및 구조",
    "security": "치안",
    "military": "군사",
    "child_alone": "보호자 없는 아동",
    "water": "식수 지원",
    "food": "식량 지원",
    "shelter": "대피 지원",
    "clothing": "의류 지원",
    "money": "금전 지원",
    "missing_people": "실종자",
    "refugees": "난민",
    "death": "사망",
    "other_aid": "기타 구호",
    "infrastructure_related": "인프라 관련",
    "transport": "교통",
    "buildings": "건물",
    "electricity": "전기",
    "tools": "도구",
    "hospitals": "병원",
    "shops": "상점",
    "aid_centers": "구호 센터",
    "other_infrastructure": "기타 인프라",
    "weather_related": "기상 관련",
    "floods": "홍수",
    "storm": "폭풍",
    "fire": "화재",
    "earthquake": "지진",
    "cold": "한파",
    "other_weather": "기타 기상",
    "direct_report": "직접 신고",
}
